In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

print("hello gaurav")

In [21]:
import numpy as np

#ARRAY CREATION
#Array creation 
#1D array
arr=np.array([1,2,3,4,5])
print(arr)
print("=============================")

#2D array
arr1=np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)
print("=============================")

#Creates an array filled with zeros
arr=np.zeros((2,3))
print(arr)
print("=============================")

#Creates an array filled with ones
arr1=np.ones((3,3))
print(arr1)
print("=============================")

arr2=np.empty((2,3))
print(arr2)
print("=============================")

#print a range 
arr=np.arange(0,10,2)
print(arr)

#Creates evenly spaced values between two numbers
arr1=np.linspace(1,20,5)
print(arr1)
print("=============================")

#Creates an identity matrix
arr3=np.eye(3)
print(arr3)
print("=============================")


#Creates an array filled with a given value
arr4=np.full((3,3),7)
print(arr4)





[1 2 3 4 5]
[[1 2 3 4]
 [5 6 7 8]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[0 2 4 6 8]
[ 1.    5.75 10.5  15.25 20.  ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
#ARRAY PROPERTIES
